# Azure App Service deployment workflow
# Added: 2025-01-07 - Automated deployment pipeline

name: Deploy to Azure App Service

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests (when available)
      run: |
        # Add test commands here when tests are implemented
        echo "Tests will be added in future updates"
    
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mroofing-erp'  # Replace with your App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

# Environment variables will be configured in Azure App Service:
# - DATABASE_URL: Azure SQL connection string
# - FLASK_ENV: production
# - SECRET_KEY: Random secure key
# - APP_NAME: Timber Roof ERP
# - APP_VERSION: 1.0.0

